import React from "react";

const NotFoundPage = () => {
  return (
    <div className="body">

      <div className="message">
        <h1 className="not-found-title">Page Not Found </h1>
        <h2 className="not-found-subtitle">404</h2>
        <p className="not-found-text">
          The specified file was not found on this website. Please check the URL for mistakes and try again.
        </p>
        <h3 className="not-found-question">Why am I seeing this?</h3>
        <p className="not-found-text">
          This page was generated by the Firebase Command-Line Interface. To modify it, edit the <code>404.html</code> file in your project's configured <code>public</code> directory.
        </p>
      </div>
    </div>
  );
};

export default NotFoundPage;
